### ISSUE TITLE
How to change the button size ?

### ISSUE THREAD

**Issue by ittianyu** [IvBaranov/MaterialFavoriteButton#10]
I found it took up 48dp on screen.
I want a smaller view.

**Comment by IvBaranov** [comment]
The size is 48 x 48 dp by default and can not be changed. This size follows minimum touch target size according to [material design guidelines](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size). 

However you can change padding to make icon smaller.  This actually was not working programmatically using builder until f17ea732173e65ea9cc0d33d15db82858b64c176. Thanks for pointing out.

**Comment by ittianyu** [comment]
Oh, why not give user a choice.

**Comment by IvBaranov** [comment]
I was not sure that one need it. I will add this function right now.

**Comment by ittianyu** [comment]
Thanks.

**Comment by IvBaranov** [comment]
Fixed in ea17c84d0edb3e58c024f845bb34402d89a57bdc.
