### ISSUE TITLE
setOnFavoriteChangeListener always triggers automatically whenever setFavorite(false/true) is set.

### ISSUE THREAD

**Issue by 2r00t2** [IvBaranov/MaterialFavoriteButton#11]
im trying to set isFavorite true or false on volley response just before setOnFavoriteChangeListener 
`try {
                    JSONObject jObj = new JSONObject(response);
                  boolean success=  jObj.getBoolean("success");
                    if(!success){
                        holder.testb.setFavorite(false);
                    }else {
                        holder.testb.setFavorite(true);
                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }`
but every time setOnFavoriteChangeListener is called on setting true or false... 
but i want setOnFavoriteChangeListener to be called only when i change state by myself....
is there any way??

**Comment by IvBaranov** [comment]
`OnFavoriteChangeListener()` is called on every state change. If you want to track users' clicks you can implement your own `OnClickListener()` for `MaterialFavoriteButton`:
```java
favorite.setOnClickListener(new OnClickListener() {
    @Override public void onClick(View v) {
        toggleFavorite();
        stateChangedByMyself(favorite.isFavorite());
     }
    });

// ...

private void stateChangedByMyself(boolean state) {
    if (state) {
        // your stuff
    }
}
```

**Comment by ursrudra** [comment]
Hi @IvBaranov,

I am unable to update the button state to true.
 i am updating as 'holder.ivFav.setFavorite(true);'  but it always showing false status button, Could you please help.
Thank you.

**Comment by IvBaranov** [comment]
@ursrudra Could you please provide _xml_ declaration of button and/or how you build it in _code_.

**Comment by ursrudra** [comment]
Hi @IvBaranov , Thank you for your quick response, here is my xml declaration.  <com.github.ivbaranov.mfb.MaterialFavoriteButton
                android:id="@+id/ivFav"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                app:mfb_rotation_duration="400"
                app:mfb_bounce_duration="700"
                app:mfb_rotation_angle="0"
                app:mfb_type="heart"
                android:tint="#22bbff"
                />

onBindViewHolder:

    @Override
    public void onBindViewHolder(final ProductViewHolder holder, final int position) {

        final Product selectedProduct = products.get(position);
        holder.tvName.setText(selectedProduct.pname.toString());
        if(selectedProduct.isFavourite())
        {
            holder.ivFav.setFavorite(true);
        }
        else
        {
            holder.ivFav.setFavorite(false);
        }

    }

**Comment by IvBaranov** [comment]
@ursrudra check your _if statement_.
Right now if product is **not favourite**, than you go to _else_ and set it button to **false state**.

**Comment by ursrudra** [comment]
@IvBaranov still same issue, 
if i keep just  holder.ivFav.setFavorite(true); without any conditions also it is not working .

**Comment by IvBaranov** [comment]
@ursrudra provide more information, right now I don't see any problems.

**Comment by pavan88** [comment]
I am also facing the same issue.
**Steps to reproduce the problem**
1. Create a recycler view add item materialFavouriteButton in the list_items
2. Implement setonFavouriteChangeListener inside onBindViewHolder.
3. From Activity initialize the Recycler View DataAdapter.
4. Set an item fav. for the first inside recyclerview (position=1)
**_### 5. Just scroll down, Now again setonFavouriteChangeListener is invoked inside setonFavouriteChangeListener_**

**Comment by IvBaranov** [comment]
@pavan88 Seems you are using method `setFavorite` on view binding. Try using `setFavoriteSuppressListener` instead to skip call of listener each time the view appears on the screen.
