### ISSUE TITLE
Calling setOnFavoriteChangeListener

### ISSUE THREAD

**Issue by alishaker** [IvBaranov/MaterialFavoriteButton#16]
When calling setFavourite it calls the setOnFavoriteChangeListener, which i guess not needed, in my case, whenever the user pressed the favorite button it calls api, so if i set it manually, it will call the api even if the user didn't clicked the favorite button

**Comment by IvBaranov** [comment]
Added a method `setFavoriteSuppressListener(bool favorite)` which changes state without calling OnFavoriteChangeListener

See also [Release notes](https://github.com/IvBaranov/MaterialFavoriteButton/releases/tag/0.1.5)
