### ISSUE TITLE
Usage in recyclerview

### ISSUE THREAD

**Issue by halilozercan** [IvBaranov/MaterialFavoriteButton#3]
If MaterialFavoriteButton used in recyclerview, it behaves like favorite is changed to false when the item view disappears from screen. Naturally, it calls favoriteChanged listener.

**Comment by IvBaranov** [comment]
This is how recycler view works. I guess the best I can do is suggest [this workaround](https://github.com/frogermcs/InstaMaterial/commit/1dcbcf491436c70cae8772bbc3cb57098810aa07).

**Comment by halilozercan** [comment]
I ended up with settings my own OnClickListener for favorite button inside onBindViewHolder method. It looked something like this

``` java
@Override
public void onBindViewHolder(final ViewHolder holder, int position) {

    favoriteButton.setFavorite(isFavorite(data.get(position)), false);

    holder.favoriteButton.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            holder.favoriteButton.toggleFavorite();
        }
    });
}
```

This prevents the weird interaction I was talking about.

**Comment by IvBaranov** [comment]
Nice workaround, I will add this note to README

**Comment by amanzan** [comment]
Thanks @halilozercan 

That fixed my issue

**Comment by zunjae** [comment]
You saved a lot of time for me @halilozercan , thanks a lot!
