### ISSUE TITLE
Can't compile in the gradle file

### ISSUE THREAD

**Issue by niennonno** [IvBaranov/MaterialFavoriteButton#4]
The project is not able to compile when you add 
`compile 'com.github.ivbaranov:MaterialFavoriteButton:0.1.1'` to the gradle file.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/12701961/10966813/1fdadf20-83dc-11e5-8b81-9ebe4b23f3dc.png)

**Comment by IvBaranov** [comment]
Please use the lower case artifact name:

`com.github.ivbaranov:materialfavoritebutton:0.1.1`

Sorry about that, I will fix README.md.

**Comment by niennonno** [comment]
Thank you!
