### ISSUE TITLE
How can we set color for favorite button/icon other than black/white ?

### ISSUE THREAD

**Issue by jssisodiya** [IvBaranov/MaterialFavoriteButton#7]
`app:mfb_color="@color/favorite_star" // yellow`
Above attribute turns the icon into white.

**Comment by IvBaranov** [comment]
Unfortunately in current realization you are only able to choose between two colors.

By specifying `mfb_color` attribute (which is enum {black, white}, not resource id) you choose between basic icons provided with library:
<img width="392" alt="2015-12-01 19 28 09" src="https://cloud.githubusercontent.com/assets/6000572/11506720/db484d6c-9861-11e5-84a5-f2e2ce0c58de.png">

So, color customization brings to customizing resource.

```
app:mfb_favorite_image="@drawable/ic_fav"       // custom favorite resource
app:mfb_not_favorite_image="drawable/ic_not_fav"// custom not favorite resource
```

**Comment by jssisodiya** [comment]
This will work
Thanks :smiley:
