### ISSUE TITLE
Wait for the response from server and then change the state of icon

### ISSUE THREAD

**Issue by HasanShaikh** [IvBaranov/MaterialFavoriteButton#9]
I want to make the button favourite after getting the response from the server.

When i click on the MaterialFavoriteButton, i am hitting the server to get the response.

If the response is positive, i want to change the button state to favourite.

So i want to wait until i get the response and then change the state.

Is it possible to do so.

Thanks

**Comment by IvBaranov** [comment]
Here is the solution:
```
yourButton.setOnClickListener(new OnClickListener() {
        @Override public void onClick(View v) {
           // send your request here
        }
      });

...
// once you get positive response
yourButton.toggleFavorite();
```

**Comment by HasanShaikh** [comment]
Thank you so much.

It is working perfectly as expected.
